name: Furby
openai_api_key: <YOUR OPENAI API KEY>
connections:
  mouth: 22
  eyebrows:
    left: 0
    right: 1
  eyes:
    left: 17
    right: 27
  controller:
    x: 13
    y: 19
    a: 21
    b: 26
